//// Used to import breweries

var config = require('../config');

//// SCHEMA:
//// NOTE: Set unused fields to false
// {
// 	code: '',
// 	logo: '',
// 	name: '',
// 	description: '',
// 	address: '',
// 	city: '',
// 	province: '',
// 	country: '',
// 	postal: '',
// 	website: '',
// 	twitter: '',
// 	instagram: '',
// 	facebook: '',
// 	youtube: '',
// 	currentTapLineup: '',
// 	currentTakeoutLineup: '',
// 	importActivated: ''
// }

module.exports = [
	{
		code: 'brassneck',
		logo: '/images/logo_brassneck_dark.png',
		name: 'Brassneck Brewery',
		description: 'The public space at Brassneck, i.e. the Growler Shop & Tasting Room are designed to have you, our customers feel as though you are part of our process. The brew house & cellar wrap around the tasting room & growler shop putting you in the very heart of the Brewery.',
		address: '2148 Main Street',
		city: 'Vancouver',
		province: 'BC',
		country: 'Canada',
		postal: false,
		website: 'http://brassneck.ca/',
		twitter: 'brassneckbrew',
		instagram: 'brassneckbrew',
		facebook: 'https://www.facebook.com/pages/Brassneck-Brewery/661469417210968',
		youtube: false,
		currentTapLineup: false,
		currentTakeoutLineup: false,
		importActivated: true
	},
	{
		code: '33acres',
		logo: '/images/logo_33acres_dark.png',
		name: '33 Acres Brewing Co.',
		description: 'Our space is located in Vancouver near a synthesis of forest and the Pacific. Itʼs here weʼve carved out a space to foster collectivity and fine craft beer. We hold that quality product exists in solidarity with working among friends, family, and community. This is an inclusive space; we value innovation in both our craft and design. Our common area was created to align these fundamentals with the simple aesthetics of our surrounding environment.',
		address: '15 W 8th Ave',
		city: 'Vancouver',
		province: 'BC',
		country: 'Canada',
		postal: false,
		website: 'http://33acresbrewing.com/',
		twitter: '33acres',
		instagram: '33acresbrewing',
		facebook: 'https://www.facebook.com/33AcresBrewing',
		youtube: false,
		currentTapLineup: false,
		currentTakeoutLineup: false,
		importActivated: true
	},
	{
		code: 'strangefellows',
	  logo: '/images/logo_strangefellows_dark.png',
		name: 'Strange Fellows Brewing',
		description: 'We are an East Vancouver craft brewery inspired by tradition and creativity, and go beyond the ordinary to celebrate that which is strange* and extraordinary. The beer we make is influenced both by old world traditions and West coast ingenuity as well as by seasonal ingredients. Our barrel programme promises unique aged beers, and we have a bit of a thing for sour beer.',
		address: '1345 Clark Drive',
		city: 'Vancouver',
		province: 'BC',
		country: 'Canada',
		postal: false,
		website: 'https://strangefellowsbrewing.com/',
		twitter: 'Strange_Fellows',
		instagram: 'strangefellowsbrewing',
		facebook: 'https://www.facebook.com/strangefellowsbrewing/',
		youtube: false,
		currentTapLineup: false,
		currentTakeoutLineup: false,
		importActivated: true
	},
	{
		code: 'steelandoak',
		logo: '/images/logo_steelandoak_dark.png',
		name: 'Steel & Oak Brewing Co.',
		description: 'Steel & Oak Brewing Co. embodies the modernness of today while remaining dedicated to the craftsmanship of years long past. Materials of strength and durability, steel and oak; house, protect and nurture what we stand for most – exceptional tasting craft beer.',
		address: '1319 Third Ave',
		city: 'New Westminister',
		province: 'BC',
		country: 'Canada',
		postal: false,
		website: 'https://steelandoak.ca/',
		twitter: 'steelandoak',
		instagram: 'steelandoak',
		facebook: 'https://www.facebook.com/steelandoak',
		youtube: false,
		currentTapLineup: false,
		currentTakeoutLineup: false,
		importActivated: true
	},
	{
		code: 'parallel49',
		logo: '/images/logo_parallel49_dark.png',
		name: 'Parallel 49 Brewing',
		description: 'The story of Parallel 49 is a story of a brewery that strives to create clever and innovative beers that are highly drinkable. It’s a story that continues to meander and morph to this day.',
		address: '1950 Triumph Street',
		city: 'Vancouver',
		province: 'BC',
		country: 'Canada',
		postal: false,
		website: 'http://parallel49brewing.com/',
		twitter: 'Parallel49Beer',
		instagram: 'parallel49beer',
		facebook: 'https://www.facebook.com/Parallel49Brewing',
		youtube: false,
		currentTapLineup: false,
		currentTakeoutLineup: false,
		importActivated: true
	},
	{
		code: 'dogwood',
		logo: '/images/logo_dogwood_dark.png',
		name: 'Dogwood Brewing',
		description: 'Armed with the will and initiative to make an impact on the beer world, Claire and Brendan Wilson created Dogwood Brewing. Claire used her years of education and brewing experience throughout British Columbia and the UK to open Vancouver\'s first organic brewery: Dogwood Brewing.',
		address: '8284 Sherbrooke Street',
		city: 'Vancouver',
		province: 'BC',
		country: 'Canada',
		postal: false,
		website: 'http://www.dogwoodbrew.com/',
		twitter: 'DogwoodBrew',
		instagram: 'dogwoodbrew',
		facebook: 'https://www.facebook.com/DogwoodBrew',
		youtube: false,
		currentTapLineup: false,
		currentTakeoutLineup: false,
		importActivated: true
	},
	{
		code: 'redtruck',
		logo: '/images/logo_redtruck_dark.png',
		name: 'Red Truck Beer',
		description: 'Armed with the will and initiative to make an impact on the beer world, Claire and Brendan Wilson created Dogwood Brewing. Claire used her years of education and brewing experience throughout British Columbia and the UK to open Vancouver\'s first organic brewery: Dogwood Brewing.',
		address: '295 East 1st Avenue',
		city: 'Vancouver',
		province: 'BC',
		country: 'Canada',
		postal: false,
		website: 'https://www.redtruckbeer.com',
		twitter: 'redtruckbeer',
		instagram: 'redtruckbeer',
		facebook: 'https://www.facebook.com/RedTruckBeer',
		youtube: 'https://www.youtube.com/user/redtruckbeer',
		currentTapLineup: false,
		currentTakeoutLineup: false,
		importActivated: true
	},
	{
		code: 'callister',
		logo: '/images/logo_callister_dark.png',
		name: 'Callister Brewing Co.',
		description: 'Opening in July 2015, Callister Brewing has established firm roots in the ever-expanding brewing neighbourhood of East Vancouver. Located at 1338 Franklin St (one block north of Hastings at Clark), Callister Brewing bridges two major craft brewery hubs intersected by Hastings St.',
		address: '1338 Franklin Street',
		city: 'Vancouver',
		province: 'BC',
		country: 'Canada',
		postal: false,
		website: 'http://www.callisterbrewing.com/',
		twitter: 'callisterbeer',
		instagram: 'callisterbeer',
		facebook: 'https://www.facebook.com/callisterbrewing',
		youtube: false,
		currentTapLineup: false,
		currentTakeoutLineup: false,
		importActivated: true
	},
	{
		code: 'strathcona',
		logo: '/images/logo_strathcona_dark.png',
		name: 'Strathcona Beer Company',
		description: 'Strathcona Beer Company is driven to provide a premium, fresh and quality product. We were founded by an impassioned group of friends with deep rooted connections to our neighbourhood and an appreciation for local and international beer. We are proudly located in the heart of Strathcona, Vancouver’s oldest and most diverse commercial and residential neighbourhood.',
		address: '895 East Hastings Street',
		city: 'Vancouver',
		province: 'BC',
		country: 'Canada',
		postal: false,
		website: 'http://www.strathconabeer.com/',
		twitter: 'strathconabeer',
		instagram: 'strathconabeer',
		facebook: 'https://www.facebook.com/strathconabeer',
		youtube: 'https://www.youtube.com/channel/UCKlIA2IuQVGCNc-N8VzUoMA',
		currentTapLineup: false,
		currentTakeoutLineup: false,
		importActivated: true
	}
]
